### ISSUE TITLE
Service Discovery feature

### ISSUE THREAD

**Issue by akak07770** [zhaohuabing/istio-redis-culster#2]
Hi @zhaohuabing,
Thank you for sharing this, its awesome :) 
I am thinking in terms of single Redis instances (which doesn't need strong consistency), kind of architecture as mentioned here which has autoscaling enabled, 
https://www.youtube.com/watch?v=U4WspAKekqM&t=2487s
![image](https://user-images.githubusercontent.com/76567016/104094702-cba19800-5292-11eb-846f-85fe237ae3b8.png)

here https://github.com/zhaohuabing/istio-redis-culster/blob/cb6cc422e536c93ea87145d30fa24c2f0f8a01c3/istio/envoyfilter-custom-redis-cluster.yaml#L19 for lb_endpoints can we use service discovery of istio service mesh?
maybe using pilot API.

**Comment by zhaohuabing** [comment]
We can use Istio for service discovery of standalone Redis instances. However, we may still need a EnvoyFilter for redis healthcheck envoy.health_checkers.redis.

https://www.envoyproxy.io/docs/envoy/latest/configuration/upstream/health_checkers/redis#config-health-checkers-redis

I created project Areaki to automate this process to support layer-7 protocols other than HTTP and gRPC in an Istio service mesh. Redis is going to be implemented soon. 

https://github.com/aeraki-framework/aeraki

**Comment by akak07770** [comment]
Sure, Thank you @zhaohuabing
