### ISSUE TITLE
Error Wrong number of arguments for specified --cluster sub command

### ISSUE THREAD

**Issue by rhzs** [zhaohuabing/istio-redis-culster#3]
I am trying to install Redis Cluster. 

I stuck when running 
```shell
❯ kubectl exec -it redis-cluster-0 -c redis -n redis -- redis-cli --cluster create --cluster-replicas 1 $(kubectl get pods -l app=redis-cluster -o jsonpath='{range.items[*]}{.status.podIP}:6379' -n redis)
```

Error
```
[ERR] Wrong number of arguments for specified --cluster sub command
command terminated with exit code 1
```

my pods 
```
❯ k get pod -n redis
NAME              READY   STATUS    RESTARTS   AGE
redis-cluster-0   1/1     Running   0          45s
redis-cluster-1   1/1     Running   0          35s
redis-cluster-2   1/1     Running   0          26s
redis-cluster-3   1/1     Running   0          16s
redis-cluster-4   1/1     Running   0          14s
redis-cluster-5   1/1     Running   0          12s
```

Istio version
```
❯ istioctl version
client version: 1.8.1
control plane version: 1.8.1
data plane version: 1.8.1 (1 proxies)
```

Any help would be appreciated! Thank you

**Comment by kyle-gta** [comment]
> I am trying to install Redis Cluster.
> 
> I stuck when running
> 
> ```shell
> ❯ kubectl exec -it redis-cluster-0 -c redis -n redis -- redis-cli --cluster create --cluster-replicas 1 $(kubectl get pods -l app=redis-cluster -o jsonpath='{range.items[*]}{.status.podIP}:6379' -n redis)
> ```
> 
> Error
> 
> ```
> [ERR] Wrong number of arguments for specified --cluster sub command
> command terminated with exit code 1
> ```
> 
> my pods
> 
> ```
> ❯ k get pod -n redis
> NAME              READY   STATUS    RESTARTS   AGE
> redis-cluster-0   1/1     Running   0          45s
> redis-cluster-1   1/1     Running   0          35s
> redis-cluster-2   1/1     Running   0          26s
> redis-cluster-3   1/1     Running   0          16s
> redis-cluster-4   1/1     Running   0          14s
> redis-cluster-5   1/1     Running   0          12s
> ```
> 
> Istio version
> 
> ```
> ❯ istioctl version
> client version: 1.8.1
> control plane version: 1.8.1
> data plane version: 1.8.1 (1 proxies)
> ```
> 
> Any help would be appreciated! Thank you

Excuse me , have you fix this ?
i hava a redis cluster
one master and two slave
i don't know how to init the cluster at first
please help me, thank you

**Comment by psigillito** [comment]
I am doing the same tutorial. It is getting hung up on the sub command: $(kubectl get pods -l app=redis-cluster -o jsonpath='{range.items[*]}{.status.podIP}:6379' -n redis)

You can work around this by manually entering the ip addresses. You can get the pod ips with the command kubetl get pods -o wide. 

Here is the command I ran (as an example): 

<img width="865" alt="example" src="https://user-images.githubusercontent.com/17969377/147689073-29becbb8-b665-40f4-8314-e7b98a0ec37b.PNG">
